## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

branches:
  only:
  - master
  - develop

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GraphSignals")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
